# Customers
- request:
    url: ^/imei-check/search/data/imei/350809920173028
    method: GET
  response:
    status: 200
    file: "Customers/customersResponse.TIT.json"
    headers:
      content-type: application/json; charset=utf-8
      server: cloudflare
